name: Test & Publish

on:
  push:
    branches: [stage]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    outputs:
      version: ${{ steps.versioning.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          # Required for nbgv to work
          fetch-depth: 0
      - name: Setup
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "8.0"
      - name: Test
        run: dotnet test --no-restore --verbosity normal --logger GitHubActions
      - id: versioning
        name: Set publish
        shell: bash
        run: |
          set -e
          version="$(nbgv get-version -v SimpleVersion)$(nbgv get-version -v PrereleaseVersion)"
          if [ -z "$(git tag -l v$version)" ] && [ -n "${{ secrets.NUGET_API_KEY }}" ]; then
            echo version=$version >> "$GITHUB_OUTPUT"
          fi

  publish:
    needs: test
    if: needs.test.outputs.version
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          fetch-depth: 0
      - name: Setup
        uses: actions/setup-dotnet@main
        with:
          dotnet-version: "8.0"
      - name: Publish
        run: |
          version=${{needs.test.outputs.version}}
          dotnet pack --include-source --no-symbols --configuration Release -p:Version=$version -p:GeneratePackageOnBuild=false
          dotnet nuget push BeatSaberModdingTools.Tasks/bin/Release/*.nupkg \
            --api-key ${{ secrets.NUGET_API_KEY }} \
            --source https://api.nuget.org/v3/index.json

      - name: Push to main
        run: |
          git tag v$version
          git push origin v$version
          git push origin HEAD:main
